In [1]:
import numpy as np

## 1. How to Creating a 3x3 Identity Matrix with Float Data Type? 

In [2]:
a = np.identity(3, dtype=float)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2. Create a 1D Array with Random Values between 0 and 1. 

In [3]:
array1 = np.random.rand(5)
array1

array([0.95860226, 0.20377971, 0.35991012, 0.83873289, 0.95823914])

## 3. Create a 2D Array with Random Integer Values. 

In [4]:
array2 = np.random.randint(5, size=(2, 4))
array2

array([[2, 2, 1, 0],
       [2, 3, 1, 3]])

## 4. Creating an Array Using a Custom Function. 

In [9]:
def cf(i, j):
    return np.random.randint(i, j, (2,4))

cf(1,7)

array([[5, 5, 5, 3],
       [1, 6, 2, 5]])

## 5. Reshaping a 1D Array into a 2D Array 

In [10]:
a = np.array([1,2,3,4])
b=a.reshape(2,2)
b

array([[1, 2],
       [3, 4]])

## 6. How to Creating a 3x3 Array of Ones? 

In [11]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 7. How to get the common items between two pythons NumPy?

## Input: a = np. array ([1,2,3,2,3,4,3,4,5,6]) b = np. array ([7,2,10,2,7,4,9,4,9,8]) Expected Output: array ([2, 4])

In [14]:
a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

## 8. From array a remove all items present in array b Input: a = np. array ([1,2,3,4,5]) b = np. array ([5,6,7,8,9]) Expected Output: array ([1,2,3,4]

In [15]:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])
c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

## 9. Limit the number of items printed in python NumPy array a to a maximum of 6 elements. a = np. arrange (15) Expected Output: array ([ 0, 1, 2, ..., 12, 13, 14] 

In [16]:
a = np.arange(15)
np.set_printoptions()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 10. Drop all nan values from a 1D NumPy array Input: np. array ([1,2,3, np.nan,5,6,7, np.nan]) Desired Output: array ([ 1., 2., 3., 5., 6., 7.]) 

In [17]:
a = np. array ([1,2,3, np.nan,5,6,7, np.nan])
b = a[~np.isnan(a)]
b

array([1., 2., 3., 5., 6., 7.])

## 11. Question: Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20. 

In [18]:
a = np.arange(1,21)
print(a)

b = a.reshape(4,5)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## 12. Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type. Change its data type to float64 and verify the change. 

In [19]:
arr1 = np.arange(24).reshape(2,3,4)
print(arr1)
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Dimension:", arr1.ndim)
print("Data type:", arr1.dtype)
print()
float_3D = arr1.astype(float)
print(float_3D)
print("Shape:", float_3D.shape)
print("Size:", float_3D.size)
print("Dimension:", float_3D.ndim)
print("Data type:", float_3D.dtype)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)
Size: 24
Dimension: 3
Data type: int32

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
Shape: (2, 3, 4)
Size: 24
Dimension: 3
Data type: float64


## 13. Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel (). Verify that the flattened array matches the original. 

In [20]:
c = np.arange(12).reshape(3,4)
print(c)
np.set_printoptions(threshold=0)
d = np.ravel(c)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2 ...  9 10 11]


## 14. Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4, 5, 6]), perform element-wise addition, subtraction, multiplication, and division. Explain the behavior when dividing by zero. 

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Divide by 0:", a/0)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Divide by 0: [inf inf inf]


C:\Users\Admin\AppData\Local\Temp\ipykernel_3168\1580672386.py:8: RuntimeWarning: divide by zero encountered in divide
  print("Divide by 0:", a/0)


## 15. Question: Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform element-wise addition using broadcasting. Explain how broadcasting rules apply in this scenario.

## In summary, broadcasting simplifies the addition process between arrays of different shapes by expanding the smaller array's dimensions, allowing for seamless element-wise operations.

In [22]:
array_2d = np.array([[1], [2], [3]])
array_1d = np.array([4,5,6])
addition = array_2d + array_1d

print("2d_array\n", array_2d)
print("1d_array\n", array_1d)
print("Addition\n", addition)

2d_array
 [[1]
 [2]
 [3]]
1d_array
 [4 5 6]
Addition
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


## 16. Question: Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying elements greater than 5. Replace all elements greater than 5 with the value 5. 

In [23]:
array = np.random.randint(0, 11, size=(4,4))
print("\nOriginal array\n", array)

mask = array > 5
print("\nBoolean masked array\n", mask)

array[mask] = 5
print("\nModified array\n", array)


Original array
 [[ 2  6  4  8]
 [ 5  5  5 10]
 [ 9  2  8  9]
 [ 2  9  4  8]]

Boolean masked array
 [[False  True False  True]
 [False False False  True]
 [ True False  True  True]
 [False  True False  True]]

Modified array
 [[2 5 4 5]
 [5 5 5 5]
 [5 2 5 5]
 [2 5 4 5]]


## 17. Question: Given a 4x4 array of random integers, use indexing and slicing to extract: 
* The entire second row 
* The last column 
* The subarray consisting of the first two rows and first two columns 

In [25]:
array = np.random.randint(0, 11, size=(4,4))
print("\nOriginal array\n", array)

second_row = array[1, :]
print("\nSecond row\n", second_row)

last_column = array[:, -1]
print("\nLast Column\n", last_column)

subarray = array[:2, :2]
print("\nSubarray with first two rows and column\n", subarray)


Original array
 [[ 2  6  7 10]
 [ 7  9  3  1]
 [ 1  7  4  3]
 [ 8  3  4  4]]

Second row
 [7 9 3 1]

Last Column
 [10  1  3  4]

Subarray with first two rows and column
 [[2 6]
 [7 9]]


## 18. Question: Describe a practical example where NumPy can be used in EDA, AI, ML, and DL, and implement a NumPy solution for a simple task in each area. 

In [26]:
# For EDA

# Simulated dataset (e.g., heights of individuals in cm)
data = np.random.randint(150, 200, size=100)  # 100 random heights
mean = np.mean(data)
std_dev = np.std(data)

print("\nMean Height:", mean)
print("\nStandard Deviation of Height:", std_dev)


Mean Height: 174.28

Standard Deviation of Height: 14.026460708247109


## 19. Question: Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the matrix. 

In [27]:
# Step 1: Create a random 4x4 matrix
matrix = np.random.rand(4, 4)
print("Random 4x4 Matrix:\n", matrix)

# Step 2: Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

# Step 3: Verify the eigenvalues by reconstructing the matrix
# Reconstruct the matrix using the formula A = V * D * V^(-1)
# where V is the matrix of eigenvectors and D is the diagonal matrix of eigenvalues
D = np.diag(eigenvalues)  # Diagonal matrix of eigenvalues
reconstructed_matrix = eigenvectors @ D @ np.linalg.inv(eigenvectors)

print("\nReconstructed Matrix:\n", reconstructed_matrix)

# Check if the original matrix and reconstructed matrix are approximately equal
print("\nAre the original and reconstructed matrices approximately equal?", np.allclose(matrix, reconstructed_matrix))

Random 4x4 Matrix:
 [[0.53676742 0.66331771 0.06566062 0.02753144]
 [0.01942772 0.84667152 0.84100667 0.50195163]
 [0.08023774 0.3271647  0.38538051 0.17966775]
 [0.67274106 0.36029137 0.30574979 0.87227539]]

Eigenvalues:
 [1.73143306+0.j         0.40130954+0.40115431j 0.40130954-0.40115431j
 0.1070427 +0.j        ]

Eigenvectors:
 [[ 0.37217724+0.j         -0.26256554+0.5514553j  -0.26256554-0.5514553j
   0.49395442+0.j        ]
 [ 0.61808498+0.j         -0.29697833-0.27029111j -0.29697833+0.27029111j
  -0.35905988+0.j        ]
 [ 0.2581728 +0.j         -0.10969049-0.01126064j -0.10969049+0.01126064j
   0.60752575+0.j        ]
 [ 0.64249659+0.j          0.67345688+0.j          0.67345688-0.j
  -0.50793454+0.j        ]]

Reconstructed Matrix:
 [[0.53676742+1.28530631e-17j 0.66331771+1.30778151e-16j
  0.06566062-3.22680684e-16j 0.02753144-9.47371122e-17j]
 [0.01942772-1.87948999e-17j 0.84667152+3.96994482e-18j
  0.84100667-3.55579683e-16j 0.50195163+1.23492678e-18j]
 [0.08023774-4.2529

## 20. Question: Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array with the original. 

In [28]:
array = np.arange(27)
print("Original array:\n", array)

reshaped_array = array.reshape((3,3,3))
print("\nReshaped array:\n", reshaped_array)

flattened_array = reshaped_array.flatten()  # we can also use ravel() function instead of flatten()
print("\nFlattened array:\n", flattened_array)

comparison = np.array_equal(array, flattened_array)
print("\nComaprison of both array:", comparison)

Original array:
 [ 0  1  2 ... 24 25 26]

Reshaped array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Flattened array:
 [ 0  1  2 ... 24 25 26]

Comaprison of both array: True


## 21. Question: Perform matrix multiplication of two 2D arrays using np.dot () and @. Compare the results and performance of both methods using a large dataset. 

In [29]:
import time
size = 1000
M = np.random.rand(size, size)   
N = np.random.rand(size, size)

# using dot() functiom
start_time_dot = time.time()
result_dot = np.dot(M, N)
end_time_dot = time.time()
time_dot = end_time_dot - start_time_dot

# using at@ function
start_time_at = time.time()
result_at = M @ N
end_time_at = time.time()
time_at = end_time_at - start_time_at

print(f"Matrix multiplication using np.dot() took {time_dot:.4f} seconds.")
print(f"Matrix multiplication using @ took {time_at:.4f} seconds.")

# Compare result
result_match = np.allclose(result_dot, result_at)
print(f"Ressult Match: {result_match}")

Matrix multiplication using np.dot() took 0.0241 seconds.
Matrix multiplication using @ took 0.0228 seconds.
Ressult Match: True


## 22. Question: Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1). Perform an element-wise operation using broadcasting and explain the result. Use np. new axis to achieve the same result without broadcasting. 

In [30]:
array_3d = np.array([[[1,2,3,4]], [[5,6,7,8]]])
array_2d = np.array([[10],[20],[30],[40]])

# Result using Broadcasting
result_broadcasting = array_3d + array_2d.T
print("Result with Broadcasting:\n", result_broadcasting)

# Result using newaxis function
array_2d_newaxis = array_2d[np.newaxis, :, :]
array_3d_newaxis = array_3d[:, :, np.newaxis]

result_nnewaxis = array_2d_newaxis + array_3d_newaxis
print("Result with newaxis:\n", result_nnewaxis)

Result with Broadcasting:
 [[[11 22 33 44]]

 [[15 26 37 48]]]
Result with newaxis:
 [[[[11 12 13 14]
   [21 22 23 24]
   [31 32 33 34]
   [41 42 43 44]]]


 [[[15 16 17 18]
   [25 26 27 28]
   [35 36 37 38]
   [45 46 47 48]]]]


## 23. Question: Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. Replace these values with their squares and leave the rest unchanged. 

In [31]:
A = np.random.rand(5,5)
print("Original array:\n", A)

mask = A < 5

A[mask] = A[mask] ** 2
print("\nModified array:\n", A)

Original array:
 [[0.53298165 0.55134871 0.19337721 0.23073841 0.13120666]
 [0.77814275 0.2152596  0.68180656 0.90594699 0.28711178]
 [0.72072423 0.78929545 0.86134827 0.54404029 0.99212111]
 [0.44655864 0.64270745 0.21920182 0.7887021  0.99719227]
 [0.09632474 0.97227017 0.53971053 0.93366035 0.8027996 ]]

Modified array:
 [[0.28406944 0.3039854  0.03739475 0.05324021 0.01721519]
 [0.60550615 0.0463367  0.46486018 0.82073996 0.08243317]
 [0.51944342 0.62298731 0.74192083 0.29597984 0.9843043 ]
 [0.19941461 0.41307286 0.04804944 0.622051   0.99439241]
 [0.00927845 0.94530928 0.29128746 0.87172165 0.6444872 ]]


## 24. Question: Given a 5x5 array of sequential integers, use slicing to: 
* Extract the diagonal elements 
* Replace the elements of the middle row with zeros 
* Flip the array vertically and horizontally 

In [ ]:
array = np.arange(1,26).reshape(5,5)
print("Original array:\n", array)

diagonal = np.diagonal(array)
print("\nDiagonal array:\n", array)

array[2, :] = 0
print("\nArray after replacing middle row with 0:\n", array)

flip = np.flipud(np.fliplr(array))
print("\nFlippped array:\n", flip)

## 25. Question: Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a specified axis. 

In [8]:
array_4d = np.random.randint(0, 100, size=(2,3,4,5))
print("Original array:\n", array_4d)

subarray = array_4d[0, :, -2:, :3]
print("\nExtracted Subarray:\n", subarray)

mean = np.mean(subarray, axis=1)
print("\nMean along axis:\n", mean)

Original array:
 [[[[90 84 22  5 73]
   [91 51 32 17 13]
   [98 14  5 68 27]
   [30 24 15 70 55]]

  [[ 3 63 46  9 46]
   [12 65 17 29 85]
   [39 67 77 13 82]
   [30 28 32 93 17]]

  [[77 42 56 12 65]
   [22 41 89 49 71]
   [93 97 41 91 58]
   [24 24 75 37 61]]]


 [[[33 94 43 97 31]
   [89 81 56 27 94]
   [77  4 25 38 55]
   [60 93 87 71 44]]

  [[13 68 25 90 69]
   [94 87 27 15 27]
   [ 6 68 66 76 42]
   [13 12 92 71 64]]

  [[36 77 64 23 69]
   [40 36 59 94 54]
   [50 95  8 90 27]
   [ 7 31 74 53 43]]]]

Extracted Subarray:
 [[[98 14  5]
  [30 24 15]]

 [[39 67 77]
  [30 28 32]]

 [[93 97 41]
  [24 24 75]]]

Mean along axis:
 [[64.  19.  10. ]
 [34.5 47.5 54.5]
 [58.5 60.5 58. ]]


## 26. Question: Given an array of shape (10, 20), reshape it to (20, 10) and (5, 40). Discuss the impact on the array's shape, size, and dimensionality. 

In [7]:
array = np.arange(200).reshape(10, 20)
print(array)

reshape1 = array.reshape(20, 10)
print("\n",reshape1)
print("\nReshaped Array (20, 10):\n", reshape1)
print("Shape:", reshape1.shape)
print("Size:", reshape1.size)
print("Dimensionality:", reshape1.ndim)

reshape2 = array.reshape(5,40)
print("\n",reshape2)
print("\nReshaped Array (5, 40):\n", reshape2)
print("Shape:", reshape2.shape)
print("Size:", reshape2.size)
print("Dimensionality:", reshape2.ndim)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]]

 [[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33 

## 27. Question: Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear algebra operations. 

In [6]:
rows, cols = 1000, 1000
large_array = np.arange(rows * cols).reshape(rows, cols)

print("Original 2D Array Shape:", large_array.shape)

reshaped_array_1 = large_array.reshape((2000, 500))
reshaped_array_2 = large_array.reshape((10, 100, 1000))

print("Reshaped Array (2000, 500):", reshaped_array_1.shape)
print("Reshaped Array (10, 100, 1000):", reshaped_array_2.shape)

flattened_array = large_array.ravel()
print("Flattened Array Shape:", flattened_array.shape)

restored_array = flattened_array.reshape(rows, cols)
print("Restored Array Shape:", restored_array.shape)

matrix_1 = np.random.rand(500, 1000)
matrix_2 = np.random.rand(1000, 500)

reshaped_matrix_1 = matrix_1.reshape(1000, 500)
reshaped_matrix_2 = matrix_2.reshape(500, 1000)

result_matrix = np.dot(reshaped_matrix_1, reshaped_matrix_2)

print("Result Matrix Shape:", result_matrix.shape)

mean_value = np.mean(flattened_array)
print("Mean of the Flattened Array:", mean_value)

Original 2D Array Shape: (1000, 1000)
Reshaped Array (2000, 500): (2000, 500)
Reshaped Array (10, 100, 1000): (10, 100, 1000)
Flattened Array Shape: (1000000,)
Restored Array Shape: (1000, 1000)
Result Matrix Shape: (1000, 1000)
Mean of the Flattened Array: 499999.5


## 28. Question: Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular part to zero. Verify the result.

In [5]:
import numpy as np

# Step 1: Create a 6x6 matrix
matrix = np.random.randint(1, 10, size=(6, 6))  # Generating a 6x6 matrix with random integers
print("Original Matrix:\n", matrix)

# Step 2: Extract the upper triangular part
upper_triangular = np.triu(matrix)  # This keeps the upper triangular part and sets the lower part to zero
print("\nUpper Triangular Part:\n", upper_triangular)

# Step 3: Set the lower triangular part to zero
matrix[np.tril_indices(6, -1)] = 0  # Set lower triangular indices to zero
print("\nMatrix after setting lower triangular part to zero:\n", matrix)

# Step 4: Verify the result
print("\nVerification (should be upper triangular):")
print(matrix)

Original Matrix:
 [[2 5 5 7 3 6]
 [7 2 1 3 7 2]
 [5 8 9 4 5 3]
 [2 5 3 4 6 1]
 [2 2 1 4 5 5]
 [3 9 7 6 3 3]]

Upper Triangular Part:
 [[2 5 5 7 3 6]
 [0 2 1 3 7 2]
 [0 0 9 4 5 3]
 [0 0 0 4 6 1]
 [0 0 0 0 5 5]
 [0 0 0 0 0 3]]

Matrix after setting lower triangular part to zero:
 [[2 5 5 7 3 6]
 [0 2 1 3 7 2]
 [0 0 9 4 5 3]
 [0 0 0 4 6 1]
 [0 0 0 0 5 5]
 [0 0 0 0 0 3]]

Verification (should be upper triangular):
[[2 5 5 7 3 6]
 [0 2 1 3 7 2]
 [0 0 9 4 5 3]
 [0 0 0 4 6 1]
 [0 0 0 0 5 5]
 [0 0 0 0 0 3]]
